# Generated by Django 3.2.8 on 2021-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categorias', models.CharField(max_length=200)),
                ('detalles', models.CharField(max_length=200)),
                ('precios', models.CharField(max_length=200)),
            ],
        ),
    ]
