# Generated by Django 3.2.8 on 2021-10-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Producto',
        ),
    ]
